services:
  redis:
    image: redis:7-alpine
    container_name: redis-rag
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
    command: redis-server --requirepass 123456
    restart: always  # 容器异常退出自动重启
    networks:
      - rag-network

  minio:
    image: minio/minio:latest
    container_name: minio-rag
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=miniorag
      - MINIO_ROOT_PASSWORD=minio123456
    volumes:
      - ~/minio-data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
